URL: "http://localhost:5001"
ENDPOINT: "/api/v1/generate"
DEFAULT_BODY: '{"stop_sequence": "\n\n", "max_length":300, "max_context_length":512, "temperature":0.8, "top_k":120, "top_a":0.0, "top_p":0.85, "typical_p":1.0, "tfs":1.0, "rep_pen":1.1, "rep_pen_range":128, "mirostat":0, "mirostat_tau":5.0, "mirostat_eta":0.1, "sampler_order":[6,0,1,3,4,2,5], "seed":-1}'
