URL: "http://localhost:5001"
ENDPOINT: "/api/v1/generate"
DEFAULT_BODY: '{"stop_sequence": "\n\n", "max_length":300, "max_context_length":2048, "temperature":1.0, "top_k":120, "top_a":0.0, "top_p":0.85, "typical_p":1.0, "tfs":1.0, "rep_pen":1.1, "rep_pen_range":128, "mirostat":0, "mirostat_tau":5.0, "mirostat_eta":0.1, "sampler_order":[6,0,1,3,4,2,5], "seed":-1}'
MEMORY_SIZE: 1024
PRE_PROMPT: 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n'
BASE_PROMPT: '### Instruction: Rewrite the following text your own words using vivid language. Text:\n\n {input_text} \n\nEnd of text.\n\n### Response:\n\n'
DIALOGUE_PROMPT: 'The following is a conversation between {character1} and {character2}. {character2_description}. Chat history: {previous_conversation}\n\n### Instruction: Write a single response as {character2}, using {character2} description.\n\n### Response:\n\n'

